{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "nyc_yelp_eda",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rajashekarv95/Yelpies/blob/main/nyc_yelp_eda.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "3HcDPpHTrzlJ",
        "outputId": "7beb156b-5a13-450e-cca1-1cf9d56dc48a",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Mounted at /content/drive\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "uyaTF4kuizNl",
        "outputId": "6c7c4a3d-b9ba-4444-9593-a25913642b27",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "!pip install sodapy"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Collecting sodapy\n",
            "  Downloading https://files.pythonhosted.org/packages/9e/74/95fb7d45bbe7f1de43caac45d7dd4807ef1e15881564a00eef489a3bb5c6/sodapy-2.1.0-py2.py3-none-any.whl\n",
            "Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.6/dist-packages (from sodapy) (2.23.0)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (2.10)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (2020.6.20)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (3.0.4)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (1.24.3)\n",
            "Installing collected packages: sodapy\n",
            "Successfully installed sodapy-2.1.0\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "izvJ80eWircf",
        "outputId": "624dd68a-bd7a-4634-983a-1bde4578d841",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 496
        }
      },
      "source": [
        "import pandas as pd\n",
        "from sodapy import Socrata\n",
        "\n",
        "app_token = 'of2oZrU7SHHnWAv18xuDk0g0H'\n",
        "\n",
        "client = Socrata(\"data.cityofnewyork.us\", app_token)\n",
        "\n",
        "# nyc open dataset identifier\n",
        "results = client.get(\"43nn-pn8j\", limit=400000)\n",
        "\n",
        "df = pd.DataFrame.from_records(results)\n",
        "df.head()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>camis</th>\n",
              "      <th>dba</th>\n",
              "      <th>boro</th>\n",
              "      <th>building</th>\n",
              "      <th>street</th>\n",
              "      <th>zipcode</th>\n",
              "      <th>phone</th>\n",
              "      <th>cuisine_description</th>\n",
              "      <th>inspection_date</th>\n",
              "      <th>action</th>\n",
              "      <th>violation_code</th>\n",
              "      <th>violation_description</th>\n",
              "      <th>critical_flag</th>\n",
              "      <th>score</th>\n",
              "      <th>record_date</th>\n",
              "      <th>inspection_type</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>community_board</th>\n",
              "      <th>council_district</th>\n",
              "      <th>census_tract</th>\n",
              "      <th>bin</th>\n",
              "      <th>bbl</th>\n",
              "      <th>nta</th>\n",
              "      <th>grade</th>\n",
              "      <th>grade_date</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>41556098</td>\n",
              "      <td>UDOM THAI</td>\n",
              "      <td>Brooklyn</td>\n",
              "      <td>661</td>\n",
              "      <td>WASHINGTON AVENUE</td>\n",
              "      <td>11238</td>\n",
              "      <td>7186228424</td>\n",
              "      <td>Thai</td>\n",
              "      <td>2017-11-30T00:00:00.000</td>\n",
              "      <td>Violations were cited in the following area(s).</td>\n",
              "      <td>02G</td>\n",
              "      <td>Cold food item held above 41º F (smoked fish a...</td>\n",
              "      <td>Y</td>\n",
              "      <td>24</td>\n",
              "      <td>2020-11-11T06:01:44.000</td>\n",
              "      <td>Cycle Inspection / Initial Inspection</td>\n",
              "      <td>40.67737501982</td>\n",
              "      <td>-73.963673693824</td>\n",
              "      <td>308</td>\n",
              "      <td>35</td>\n",
              "      <td>020500</td>\n",
              "      <td>3028591</td>\n",
              "      <td>3011540012</td>\n",
              "      <td>BK64</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>50080072</td>\n",
              "      <td>BETTER GOURMET</td>\n",
              "      <td>Staten Island</td>\n",
              "      <td>4077</td>\n",
              "      <td>VICTORY BOULEVARD</td>\n",
              "      <td>10314</td>\n",
              "      <td>7189839111</td>\n",
              "      <td>Sandwiches/Salads/Mixed Buffet</td>\n",
              "      <td>2018-09-18T00:00:00.000</td>\n",
              "      <td>Violations were cited in the following area(s).</td>\n",
              "      <td>02B</td>\n",
              "      <td>Hot food item not held at or above 140º F.</td>\n",
              "      <td>Y</td>\n",
              "      <td>13</td>\n",
              "      <td>2020-11-11T06:01:44.000</td>\n",
              "      <td>Pre-permit (Operational) / Initial Inspection</td>\n",
              "      <td>40.592228547243</td>\n",
              "      <td>-74.18977061546</td>\n",
              "      <td>502</td>\n",
              "      <td>50</td>\n",
              "      <td>029102</td>\n",
              "      <td>5166713</td>\n",
              "      <td>5027710006</td>\n",
              "      <td>SI05</td>\n",
              "      <td>A</td>\n",
              "      <td>2018-09-18T00:00:00.000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>50036869</td>\n",
              "      <td>PAK LAHORI CHILLI</td>\n",
              "      <td>Brooklyn</td>\n",
              "      <td>1026</td>\n",
              "      <td>CONEY ISLAND AVENUE</td>\n",
              "      <td>11230</td>\n",
              "      <td>7188591400</td>\n",
              "      <td>Indian</td>\n",
              "      <td>2018-09-13T00:00:00.000</td>\n",
              "      <td>Establishment Closed by DOHMH.  Violations wer...</td>\n",
              "      <td>04L</td>\n",
              "      <td>Evidence of mice or live mice present in facil...</td>\n",
              "      <td>Y</td>\n",
              "      <td>57</td>\n",
              "      <td>2020-11-11T06:01:44.000</td>\n",
              "      <td>Cycle Inspection / Initial Inspection</td>\n",
              "      <td>40.632652556679</td>\n",
              "      <td>-73.966893820243</td>\n",
              "      <td>314</td>\n",
              "      <td>40</td>\n",
              "      <td>048200</td>\n",
              "      <td>3128204</td>\n",
              "      <td>3054290025</td>\n",
              "      <td>BK42</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>40788886</td>\n",
              "      <td>STARBUCKS</td>\n",
              "      <td>Manhattan</td>\n",
              "      <td>750</td>\n",
              "      <td>6 AVENUE</td>\n",
              "      <td>10010</td>\n",
              "      <td>6462307208</td>\n",
              "      <td>Café/Coffee/Tea</td>\n",
              "      <td>2017-05-26T00:00:00.000</td>\n",
              "      <td>Violations were cited in the following area(s).</td>\n",
              "      <td>10F</td>\n",
              "      <td>Non-food contact surface improperly constructe...</td>\n",
              "      <td>N</td>\n",
              "      <td>2</td>\n",
              "      <td>2020-11-11T06:01:44.000</td>\n",
              "      <td>Cycle Inspection / Initial Inspection</td>\n",
              "      <td>40.744007027064</td>\n",
              "      <td>-73.991984743351</td>\n",
              "      <td>105</td>\n",
              "      <td>03</td>\n",
              "      <td>005800</td>\n",
              "      <td>1085951</td>\n",
              "      <td>1008260001</td>\n",
              "      <td>MN13</td>\n",
              "      <td>A</td>\n",
              "      <td>2017-05-26T00:00:00.000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>41242907</td>\n",
              "      <td>CROSS BRONX PIZZERIA</td>\n",
              "      <td>Bronx</td>\n",
              "      <td>1105</td>\n",
              "      <td>CASTLE HILL AVENUE</td>\n",
              "      <td>10472</td>\n",
              "      <td>7188928459</td>\n",
              "      <td>Pizza</td>\n",
              "      <td>2019-01-03T00:00:00.000</td>\n",
              "      <td>Violations were cited in the following area(s).</td>\n",
              "      <td>08A</td>\n",
              "      <td>Facility not vermin proof. Harborage or condit...</td>\n",
              "      <td>N</td>\n",
              "      <td>11</td>\n",
              "      <td>2020-11-11T06:01:44.000</td>\n",
              "      <td>Cycle Inspection / Initial Inspection</td>\n",
              "      <td>40.829889458995</td>\n",
              "      <td>-73.850569768038</td>\n",
              "      <td>209</td>\n",
              "      <td>18</td>\n",
              "      <td>007800</td>\n",
              "      <td>2026433</td>\n",
              "      <td>2038090044</td>\n",
              "      <td>BX59</td>\n",
              "      <td>A</td>\n",
              "      <td>2019-01-03T00:00:00.000</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "      camis                   dba  ... grade               grade_date\n",
              "0  41556098             UDOM THAI  ...   NaN                      NaN\n",
              "1  50080072        BETTER GOURMET  ...     A  2018-09-18T00:00:00.000\n",
              "2  50036869     PAK LAHORI CHILLI  ...   NaN                      NaN\n",
              "3  40788886             STARBUCKS  ...     A  2017-05-26T00:00:00.000\n",
              "4  41242907  CROSS BRONX PIZZERIA  ...     A  2019-01-03T00:00:00.000\n",
              "\n",
              "[5 rows x 26 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 3
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "xDrnZeFniwiZ",
        "outputId": "14b5ed8d-a44b-4e77-bcfe-68341877646e",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "df.shape"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(400000, 26)"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 21
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "MHfIkGeTEZzd"
      },
      "source": [
        "## Filter out dates with an incorrect date format \n",
        "df = df[df['inspection_date'] != '1900-01-01T00:00:00.000'] "
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ft9fvKSMj4lu"
      },
      "source": [
        "business_df = pd.read_json('/content/drive/My Drive/1001/yelp_academic_dataset_business.json', orient='records', lines=True)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "hV_Z1yw3liD5",
        "outputId": "69539f40-ea5a-4d58-eb87-e9eddfafbe07",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "source": [
        "business_df"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>business_id</th>\n",
              "      <th>name</th>\n",
              "      <th>address</th>\n",
              "      <th>city</th>\n",
              "      <th>state</th>\n",
              "      <th>postal_code</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>stars</th>\n",
              "      <th>review_count</th>\n",
              "      <th>is_open</th>\n",
              "      <th>attributes</th>\n",
              "      <th>categories</th>\n",
              "      <th>hours</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>f9NumwFMBDn751xgFiRbNA</td>\n",
              "      <td>The Range At Lake Norman</td>\n",
              "      <td>10913 Bailey Rd</td>\n",
              "      <td>Cornelius</td>\n",
              "      <td>NC</td>\n",
              "      <td>28031</td>\n",
              "      <td>35.462724</td>\n",
              "      <td>-80.852612</td>\n",
              "      <td>3.5</td>\n",
              "      <td>36</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'BikePa...</td>\n",
              "      <td>Active Life, Gun/Rifle Ranges, Guns &amp; Ammo, Sh...</td>\n",
              "      <td>{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Yzvjg0SayhoZgCljUJRF9Q</td>\n",
              "      <td>Carlos Santo, NMD</td>\n",
              "      <td>8880 E Via Linda, Ste 107</td>\n",
              "      <td>Scottsdale</td>\n",
              "      <td>AZ</td>\n",
              "      <td>85258</td>\n",
              "      <td>33.569404</td>\n",
              "      <td>-111.890264</td>\n",
              "      <td>5.0</td>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>{'GoodForKids': 'True', 'ByAppointmentOnly': '...</td>\n",
              "      <td>Health &amp; Medical, Fitness &amp; Instruction, Yoga,...</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>XNoUzKckATkOD1hP6vghZg</td>\n",
              "      <td>Felinus</td>\n",
              "      <td>3554 Rue Notre-Dame O</td>\n",
              "      <td>Montreal</td>\n",
              "      <td>QC</td>\n",
              "      <td>H4C 1P4</td>\n",
              "      <td>45.479984</td>\n",
              "      <td>-73.580070</td>\n",
              "      <td>5.0</td>\n",
              "      <td>5</td>\n",
              "      <td>1</td>\n",
              "      <td>None</td>\n",
              "      <td>Pets, Pet Services, Pet Groomers</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>6OAZjbxqM5ol29BuHsil3w</td>\n",
              "      <td>Nevada House of Hose</td>\n",
              "      <td>1015 Sharp Cir</td>\n",
              "      <td>North Las Vegas</td>\n",
              "      <td>NV</td>\n",
              "      <td>89030</td>\n",
              "      <td>36.219728</td>\n",
              "      <td>-115.127725</td>\n",
              "      <td>2.5</td>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'ByAppo...</td>\n",
              "      <td>Hardware Stores, Home Services, Building Suppl...</td>\n",
              "      <td>{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>51M2Kk903DFYI6gnB5I6SQ</td>\n",
              "      <td>USE MY GUY SERVICES LLC</td>\n",
              "      <td>4827 E Downing Cir</td>\n",
              "      <td>Mesa</td>\n",
              "      <td>AZ</td>\n",
              "      <td>85205</td>\n",
              "      <td>33.428065</td>\n",
              "      <td>-111.726648</td>\n",
              "      <td>4.5</td>\n",
              "      <td>26</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'ByAppo...</td>\n",
              "      <td>Home Services, Plumbing, Electricians, Handyma...</td>\n",
              "      <td>{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209388</th>\n",
              "      <td>9Q0fPWAjUweoFDk0kafuzQ</td>\n",
              "      <td>Nishi Sushi</td>\n",
              "      <td>9750 Weston Road</td>\n",
              "      <td>Vaughan</td>\n",
              "      <td>ON</td>\n",
              "      <td>L4H 2P2</td>\n",
              "      <td>43.838555</td>\n",
              "      <td>-79.559823</td>\n",
              "      <td>4.0</td>\n",
              "      <td>5</td>\n",
              "      <td>0</td>\n",
              "      <td>{'Ambience': '{'romantic': False, 'intimate': ...</td>\n",
              "      <td>Japanese, Sushi Bars, Restaurants</td>\n",
              "      <td>{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209389</th>\n",
              "      <td>PotiAhtDMYMNsJCzV0oLAw</td>\n",
              "      <td>Walmart</td>\n",
              "      <td>3240 Wilkinson Blvd</td>\n",
              "      <td>Charlotte</td>\n",
              "      <td>NC</td>\n",
              "      <td>28208</td>\n",
              "      <td>35.226307</td>\n",
              "      <td>-80.893539</td>\n",
              "      <td>2.0</td>\n",
              "      <td>13</td>\n",
              "      <td>0</td>\n",
              "      <td>{'RestaurantsPriceRange2': '1', 'BusinessParki...</td>\n",
              "      <td>Department Stores, Food, Mobile Phones, Fashio...</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209390</th>\n",
              "      <td>SYa2j1boLF8DcGVOYfHPcA</td>\n",
              "      <td>Five Guys</td>\n",
              "      <td>7014-590 E Camelback Rd</td>\n",
              "      <td>Scottsdale</td>\n",
              "      <td>AZ</td>\n",
              "      <td>85251</td>\n",
              "      <td>33.504062</td>\n",
              "      <td>-111.929431</td>\n",
              "      <td>3.5</td>\n",
              "      <td>97</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'Restau...</td>\n",
              "      <td>American (New), Food, Burgers, Restaurants, Fa...</td>\n",
              "      <td>{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209391</th>\n",
              "      <td>RSSIsgO00OuWQTRoITacpA</td>\n",
              "      <td>Indian Trail Dog Training</td>\n",
              "      <td></td>\n",
              "      <td>Indian Trail</td>\n",
              "      <td>NC</td>\n",
              "      <td>28079</td>\n",
              "      <td>35.101965</td>\n",
              "      <td>-80.599385</td>\n",
              "      <td>5.0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>None</td>\n",
              "      <td>Pet Services, Pet Training, Pets</td>\n",
              "      <td>{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209392</th>\n",
              "      <td>tOcYmewXFhQeZh3V42ymwg</td>\n",
              "      <td>Kudlow Ye</td>\n",
              "      <td>21 St Clair Avenue E, Suite 401</td>\n",
              "      <td>Toronto</td>\n",
              "      <td>ON</td>\n",
              "      <td>M4T 1L9</td>\n",
              "      <td>43.688214</td>\n",
              "      <td>-79.392756</td>\n",
              "      <td>5.0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>None</td>\n",
              "      <td>Tax Services, Professional Services, Accountan...</td>\n",
              "      <td>{'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ...</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>209393 rows × 14 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "                   business_id  ...                                              hours\n",
              "0       f9NumwFMBDn751xgFiRbNA  ...  {'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'...\n",
              "1       Yzvjg0SayhoZgCljUJRF9Q  ...                                               None\n",
              "2       XNoUzKckATkOD1hP6vghZg  ...                                               None\n",
              "3       6OAZjbxqM5ol29BuHsil3w  ...  {'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ...\n",
              "4       51M2Kk903DFYI6gnB5I6SQ  ...  {'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '...\n",
              "...                        ...  ...                                                ...\n",
              "209388  9Q0fPWAjUweoFDk0kafuzQ  ...  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...\n",
              "209389  PotiAhtDMYMNsJCzV0oLAw  ...                                               None\n",
              "209390  SYa2j1boLF8DcGVOYfHPcA  ...  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...\n",
              "209391  RSSIsgO00OuWQTRoITacpA  ...  {'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '...\n",
              "209392  tOcYmewXFhQeZh3V42ymwg  ...  {'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ...\n",
              "\n",
              "[209393 rows x 14 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 6
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "I_32KuMhtIKM",
        "outputId": "158675ed-2d5a-416b-f0a6-c01a475bbea5",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 731
        }
      },
      "source": [
        "business_df[business_df['state'] == 'NY']"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>business_id</th>\n",
              "      <th>name</th>\n",
              "      <th>address</th>\n",
              "      <th>city</th>\n",
              "      <th>state</th>\n",
              "      <th>postal_code</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>stars</th>\n",
              "      <th>review_count</th>\n",
              "      <th>is_open</th>\n",
              "      <th>attributes</th>\n",
              "      <th>categories</th>\n",
              "      <th>hours</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>11316</th>\n",
              "      <td>XphmlM6c1a2gJ9dDv0MTEQ</td>\n",
              "      <td>US Immigration</td>\n",
              "      <td>234 W Service Rd</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>45.006670</td>\n",
              "      <td>-73.454383</td>\n",
              "      <td>3.5</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>None</td>\n",
              "      <td>Public Services &amp; Government</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>13122</th>\n",
              "      <td>0Ur9usWBEN-fPvMgfmqC1A</td>\n",
              "      <td>Contact Lens King</td>\n",
              "      <td>30 Lawrence Paquette Dr</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.985468</td>\n",
              "      <td>-73.424611</td>\n",
              "      <td>2.0</td>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>None</td>\n",
              "      <td>Shopping, Personal Shopping, Eyewear &amp; Opticia...</td>\n",
              "      <td>{'Monday': '8:30-18:0', 'Tuesday': '8:30-18:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>36116</th>\n",
              "      <td>Ya-HZZrzMWYSBtGyLajDQg</td>\n",
              "      <td>Nathan's Famous</td>\n",
              "      <td>1038 State Rt 11</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.981140</td>\n",
              "      <td>-73.458718</td>\n",
              "      <td>4.0</td>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>{'RestaurantsAttire': 'u'casual'', 'Wheelchair...</td>\n",
              "      <td>Hot Dogs, Gas Stations, Burgers, Food Stands, ...</td>\n",
              "      <td>{'Monday': '10:0-21:0', 'Tuesday': '10:0-21:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>36930</th>\n",
              "      <td>Uz77JHl5e6zlGa-71-6_dA</td>\n",
              "      <td>China Buffet</td>\n",
              "      <td>876 State Rt 11</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.979672</td>\n",
              "      <td>-73.444904</td>\n",
              "      <td>2.5</td>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>{'RestaurantsReservations': 'False', 'WiFi': '...</td>\n",
              "      <td>Restaurants, Buffets, Szechuan, Chinese, Canto...</td>\n",
              "      <td>{'Monday': '10:0-23:0', 'Tuesday': '10:0-23:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>41719</th>\n",
              "      <td>f5Pg89x-2xek78E9KHMhNg</td>\n",
              "      <td>Lakeside Coffee</td>\n",
              "      <td>109 Lake St</td>\n",
              "      <td>Rouses Point</td>\n",
              "      <td>NY</td>\n",
              "      <td>12979</td>\n",
              "      <td>44.993181</td>\n",
              "      <td>-73.364154</td>\n",
              "      <td>4.5</td>\n",
              "      <td>22</td>\n",
              "      <td>1</td>\n",
              "      <td>{'WiFi': 'u'free'', 'BusinessParking': '{'gara...</td>\n",
              "      <td>Sandwiches, Restaurants, Salad, Coffee &amp; Tea, ...</td>\n",
              "      <td>{'Tuesday': '7:0-15:0', 'Wednesday': '7:0-15:0...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>47496</th>\n",
              "      <td>sY2TrIpQaS8kFDI8GRGS3Q</td>\n",
              "      <td>Sandy's Deli &amp; Catering</td>\n",
              "      <td>133 Lake St</td>\n",
              "      <td>Rouses Point</td>\n",
              "      <td>NY</td>\n",
              "      <td>12979</td>\n",
              "      <td>44.992213</td>\n",
              "      <td>-73.363784</td>\n",
              "      <td>2.5</td>\n",
              "      <td>7</td>\n",
              "      <td>1</td>\n",
              "      <td>{'RestaurantsAttire': 'u'casual'', 'Restaurant...</td>\n",
              "      <td>Delis, Restaurants</td>\n",
              "      <td>{'Monday': '9:0-21:0', 'Tuesday': '9:0-21:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>51634</th>\n",
              "      <td>6029Vtm4LVYGPLm00htXrQ</td>\n",
              "      <td>Maplefields Champ Irving</td>\n",
              "      <td>3 Spiegel Dr, Ste 3</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.980310</td>\n",
              "      <td>-73.454753</td>\n",
              "      <td>4.0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>{'RestaurantsPriceRange2': '1', 'BusinessParki...</td>\n",
              "      <td>Convenience Stores, Automotive, Gas Stations, ...</td>\n",
              "      <td>{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>59197</th>\n",
              "      <td>ZDf_G8xgtkqqaDfuuJ2GzQ</td>\n",
              "      <td>Yves Rocher</td>\n",
              "      <td></td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.965140</td>\n",
              "      <td>-73.434300</td>\n",
              "      <td>4.0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>None</td>\n",
              "      <td>Beauty &amp; Spas, Cosmetics &amp; Beauty Supply, Shop...</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>63345</th>\n",
              "      <td>LbM7p-cI0dUCkaUzOyFMTw</td>\n",
              "      <td>McDonald's</td>\n",
              "      <td>1044 Rte 11</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.981470</td>\n",
              "      <td>-73.459850</td>\n",
              "      <td>2.0</td>\n",
              "      <td>13</td>\n",
              "      <td>1</td>\n",
              "      <td>{'NoiseLevel': 'u'quiet'', 'Alcohol': 'u'none'...</td>\n",
              "      <td>Restaurants, Fast Food, Coffee &amp; Tea, Food, Bu...</td>\n",
              "      <td>{'Monday': '5:0-23:0', 'Tuesday': '5:0-23:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>85450</th>\n",
              "      <td>V-uUDuDnUMqUWPjNULqPOA</td>\n",
              "      <td>Freeport Forwarding</td>\n",
              "      <td>1320 State Rt 9</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.994101</td>\n",
              "      <td>-73.454979</td>\n",
              "      <td>4.5</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'False'}</td>\n",
              "      <td>Local Services, Shipping Centers</td>\n",
              "      <td>{'Monday': '7:0-19:0', 'Tuesday': '7:0-19:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>89780</th>\n",
              "      <td>0oyzNutZ--rBqP_boeegPg</td>\n",
              "      <td>Best Friends Family Diner</td>\n",
              "      <td>13 Lake St</td>\n",
              "      <td>Rouses Point</td>\n",
              "      <td>NY</td>\n",
              "      <td>12979</td>\n",
              "      <td>44.999192</td>\n",
              "      <td>-73.366007</td>\n",
              "      <td>3.0</td>\n",
              "      <td>11</td>\n",
              "      <td>1</td>\n",
              "      <td>{'NoiseLevel': ''quiet'', 'RestaurantsTakeOut'...</td>\n",
              "      <td>Restaurants, American (New), American (Traditi...</td>\n",
              "      <td>{'Monday': '6:0-20:0', 'Tuesday': '6:0-20:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>109506</th>\n",
              "      <td>BmZu5ackYYCrgQIaJ3-r9A</td>\n",
              "      <td>Angelo's Pizza &amp; Grill</td>\n",
              "      <td>44 Champlain St</td>\n",
              "      <td>Rouses Point</td>\n",
              "      <td>NY</td>\n",
              "      <td>12979</td>\n",
              "      <td>44.983284</td>\n",
              "      <td>-73.368326</td>\n",
              "      <td>3.0</td>\n",
              "      <td>21</td>\n",
              "      <td>1</td>\n",
              "      <td>{'GoodForKids': 'True', 'RestaurantsReservatio...</td>\n",
              "      <td>American (Traditional), Pizza, Italian, Restau...</td>\n",
              "      <td>{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>112794</th>\n",
              "      <td>Sm1aTKiMrBRUmpbdVg5wAg</td>\n",
              "      <td>Casa Capitano</td>\n",
              "      <td>216 Lake St</td>\n",
              "      <td>Rouses Point</td>\n",
              "      <td>NY</td>\n",
              "      <td>12979</td>\n",
              "      <td>44.983355</td>\n",
              "      <td>-73.363455</td>\n",
              "      <td>4.5</td>\n",
              "      <td>12</td>\n",
              "      <td>1</td>\n",
              "      <td>{'RestaurantsReservations': 'True', 'Restauran...</td>\n",
              "      <td>Restaurants, Sicilian, Pizza, Italian, New Mex...</td>\n",
              "      <td>{'Thursday': '16:0-21:0', 'Friday': '16:0-21:0...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>123973</th>\n",
              "      <td>jH19V2I9fIslnNhDzPmdkA</td>\n",
              "      <td>Sandi's Kountry Kitchen</td>\n",
              "      <td>2539 State Rte 11</td>\n",
              "      <td>Mooers</td>\n",
              "      <td>NY</td>\n",
              "      <td>12958</td>\n",
              "      <td>44.959731</td>\n",
              "      <td>-73.592460</td>\n",
              "      <td>5.0</td>\n",
              "      <td>10</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessParking': '{'garage': False, 'street...</td>\n",
              "      <td>Diners, American (Traditional), Restaurants, B...</td>\n",
              "      <td>{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:30', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>160057</th>\n",
              "      <td>WCei-r9iAqxEIFX40zOebA</td>\n",
              "      <td>Pizza Plus</td>\n",
              "      <td>881 Rte 11</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.978459</td>\n",
              "      <td>-73.444889</td>\n",
              "      <td>4.5</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>{'RestaurantsTakeOut': 'True'}</td>\n",
              "      <td>Restaurants, Pizza</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>161947</th>\n",
              "      <td>NVsv96we6iTkEClbSlWd5A</td>\n",
              "      <td>Anchorage Hotel</td>\n",
              "      <td>164 Lake St</td>\n",
              "      <td>Rouses Point</td>\n",
              "      <td>NY</td>\n",
              "      <td>12979</td>\n",
              "      <td>44.988113</td>\n",
              "      <td>-73.364757</td>\n",
              "      <td>1.5</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>{'WiFi': 'u'free'', 'RestaurantsPriceRange2': ...</td>\n",
              "      <td>Hotels &amp; Travel, Hotels, Event Planning &amp; Serv...</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>162242</th>\n",
              "      <td>3lFUdYf2zfFxrm8LIpupBw</td>\n",
              "      <td>Matt &amp; Nat</td>\n",
              "      <td>2002 Ridge Rd</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.977461</td>\n",
              "      <td>-73.449769</td>\n",
              "      <td>1.5</td>\n",
              "      <td>60</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'Restau...</td>\n",
              "      <td>Shopping, Fashion, Accessories</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>163470</th>\n",
              "      <td>-5Kbw0m7lpLDAQSX5t-fVA</td>\n",
              "      <td>Williamsburg Smile Design</td>\n",
              "      <td>189 N 9th St</td>\n",
              "      <td>Brooklyn</td>\n",
              "      <td>NY</td>\n",
              "      <td>11211</td>\n",
              "      <td>33.584717</td>\n",
              "      <td>-112.062490</td>\n",
              "      <td>3.0</td>\n",
              "      <td>82</td>\n",
              "      <td>1</td>\n",
              "      <td>{'ByAppointmentOnly': 'True', 'BusinessAccepts...</td>\n",
              "      <td>Dentists, Cosmetic Dentists, Orthodontists, He...</td>\n",
              "      <td>{'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>164374</th>\n",
              "      <td>-37cHdR8Z4Qrql6b6VoB9w</td>\n",
              "      <td>Dunkin'</td>\n",
              "      <td>1038 State Route 11</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.981476</td>\n",
              "      <td>-73.459218</td>\n",
              "      <td>1.0</td>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>{'OutdoorSeating': 'False', 'BusinessAcceptsCr...</td>\n",
              "      <td>Bagels, Food, Donuts, Coffee &amp; Tea</td>\n",
              "      <td>{'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>164875</th>\n",
              "      <td>6ipr7nnwrzf_o3MGD-8nlA</td>\n",
              "      <td>Gino's Pizza</td>\n",
              "      <td>46 Lake St</td>\n",
              "      <td>Rouses Point</td>\n",
              "      <td>NY</td>\n",
              "      <td>12979</td>\n",
              "      <td>44.995887</td>\n",
              "      <td>-73.365709</td>\n",
              "      <td>4.5</td>\n",
              "      <td>17</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'Restau...</td>\n",
              "      <td>Restaurants, Pizza</td>\n",
              "      <td>None</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>166071</th>\n",
              "      <td>M8v5TVWQu-mw6Qn3SPc1aQ</td>\n",
              "      <td>American Parcel Services</td>\n",
              "      <td>100 Walnut St, Ste 19</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.985025</td>\n",
              "      <td>-73.433969</td>\n",
              "      <td>2.5</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True'}</td>\n",
              "      <td>Shipping Centers, Local Services, Professional...</td>\n",
              "      <td>{'Monday': '8:0-16:30', 'Tuesday': '8:0-16:30'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>171377</th>\n",
              "      <td>7LBGPfgMLMBVpf3KavA0LA</td>\n",
              "      <td>Safari Beauty Studio</td>\n",
              "      <td>9213 165th St</td>\n",
              "      <td>New York</td>\n",
              "      <td>NY</td>\n",
              "      <td>11433</td>\n",
              "      <td>36.045719</td>\n",
              "      <td>-115.313391</td>\n",
              "      <td>4.0</td>\n",
              "      <td>16</td>\n",
              "      <td>1</td>\n",
              "      <td>{'RestaurantsPriceRange2': '2', 'BikeParking':...</td>\n",
              "      <td>Cosmetics &amp; Beauty Supply, Makeup Artists, Wig...</td>\n",
              "      <td>{'Monday': '9:30-19:0', 'Wednesday': '9:30-19:...</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "                   business_id  ...                                              hours\n",
              "11316   XphmlM6c1a2gJ9dDv0MTEQ  ...                                               None\n",
              "13122   0Ur9usWBEN-fPvMgfmqC1A  ...  {'Monday': '8:30-18:0', 'Tuesday': '8:30-18:0'...\n",
              "36116   Ya-HZZrzMWYSBtGyLajDQg  ...  {'Monday': '10:0-21:0', 'Tuesday': '10:0-21:0'...\n",
              "36930   Uz77JHl5e6zlGa-71-6_dA  ...  {'Monday': '10:0-23:0', 'Tuesday': '10:0-23:0'...\n",
              "41719   f5Pg89x-2xek78E9KHMhNg  ...  {'Tuesday': '7:0-15:0', 'Wednesday': '7:0-15:0...\n",
              "47496   sY2TrIpQaS8kFDI8GRGS3Q  ...  {'Monday': '9:0-21:0', 'Tuesday': '9:0-21:0', ...\n",
              "51634   6029Vtm4LVYGPLm00htXrQ  ...  {'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...\n",
              "59197   ZDf_G8xgtkqqaDfuuJ2GzQ  ...                                               None\n",
              "63345   LbM7p-cI0dUCkaUzOyFMTw  ...  {'Monday': '5:0-23:0', 'Tuesday': '5:0-23:0', ...\n",
              "85450   V-uUDuDnUMqUWPjNULqPOA  ...  {'Monday': '7:0-19:0', 'Tuesday': '7:0-19:0', ...\n",
              "89780   0oyzNutZ--rBqP_boeegPg  ...  {'Monday': '6:0-20:0', 'Tuesday': '6:0-20:0', ...\n",
              "109506  BmZu5ackYYCrgQIaJ3-r9A  ...  {'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'...\n",
              "112794  Sm1aTKiMrBRUmpbdVg5wAg  ...  {'Thursday': '16:0-21:0', 'Friday': '16:0-21:0...\n",
              "123973  jH19V2I9fIslnNhDzPmdkA  ...  {'Monday': '0:0-0:0', 'Tuesday': '7:0-19:30', ...\n",
              "160057  WCei-r9iAqxEIFX40zOebA  ...                                               None\n",
              "161947  NVsv96we6iTkEClbSlWd5A  ...                                               None\n",
              "162242  3lFUdYf2zfFxrm8LIpupBw  ...                                               None\n",
              "163470  -5Kbw0m7lpLDAQSX5t-fVA  ...  {'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ...\n",
              "164374  -37cHdR8Z4Qrql6b6VoB9w  ...  {'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ...\n",
              "164875  6ipr7nnwrzf_o3MGD-8nlA  ...                                               None\n",
              "166071  M8v5TVWQu-mw6Qn3SPc1aQ  ...  {'Monday': '8:0-16:30', 'Tuesday': '8:0-16:30'...\n",
              "171377  7LBGPfgMLMBVpf3KavA0LA  ...  {'Monday': '9:30-19:0', 'Wednesday': '9:30-19:...\n",
              "\n",
              "[22 rows x 14 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 15
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "PggfiMm1rH0Z",
        "outputId": "bbd259ce-c116-4c72-d9fb-ea8c66eb235f",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 419
        }
      },
      "source": [
        "pd.read_csv('/content/drive/My Drive/1001/yelp_business.csv')"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>business_id</th>\n",
              "      <th>name</th>\n",
              "      <th>address</th>\n",
              "      <th>city</th>\n",
              "      <th>state</th>\n",
              "      <th>postal_code</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>stars</th>\n",
              "      <th>review_count</th>\n",
              "      <th>is_open</th>\n",
              "      <th>attributes</th>\n",
              "      <th>categories</th>\n",
              "      <th>hours</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>f9NumwFMBDn751xgFiRbNA</td>\n",
              "      <td>The Range At Lake Norman</td>\n",
              "      <td>10913 Bailey Rd</td>\n",
              "      <td>Cornelius</td>\n",
              "      <td>NC</td>\n",
              "      <td>28031</td>\n",
              "      <td>35.462724</td>\n",
              "      <td>-80.852612</td>\n",
              "      <td>3.5</td>\n",
              "      <td>36</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'BikePa...</td>\n",
              "      <td>Active Life, Gun/Rifle Ranges, Guns &amp; Ammo, Sh...</td>\n",
              "      <td>{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Yzvjg0SayhoZgCljUJRF9Q</td>\n",
              "      <td>Carlos Santo, NMD</td>\n",
              "      <td>8880 E Via Linda, Ste 107</td>\n",
              "      <td>Scottsdale</td>\n",
              "      <td>AZ</td>\n",
              "      <td>85258</td>\n",
              "      <td>33.569404</td>\n",
              "      <td>-111.890264</td>\n",
              "      <td>5.0</td>\n",
              "      <td>4</td>\n",
              "      <td>1</td>\n",
              "      <td>{'GoodForKids': 'True', 'ByAppointmentOnly': '...</td>\n",
              "      <td>Health &amp; Medical, Fitness &amp; Instruction, Yoga,...</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>XNoUzKckATkOD1hP6vghZg</td>\n",
              "      <td>Felinus</td>\n",
              "      <td>3554 Rue Notre-Dame O</td>\n",
              "      <td>Montreal</td>\n",
              "      <td>QC</td>\n",
              "      <td>H4C 1P4</td>\n",
              "      <td>45.479984</td>\n",
              "      <td>-73.580070</td>\n",
              "      <td>5.0</td>\n",
              "      <td>5</td>\n",
              "      <td>1</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Pets, Pet Services, Pet Groomers</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>6OAZjbxqM5ol29BuHsil3w</td>\n",
              "      <td>Nevada House of Hose</td>\n",
              "      <td>1015 Sharp Cir</td>\n",
              "      <td>North Las Vegas</td>\n",
              "      <td>NV</td>\n",
              "      <td>89030</td>\n",
              "      <td>36.219728</td>\n",
              "      <td>-115.127725</td>\n",
              "      <td>2.5</td>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'ByAppo...</td>\n",
              "      <td>Hardware Stores, Home Services, Building Suppl...</td>\n",
              "      <td>{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>51M2Kk903DFYI6gnB5I6SQ</td>\n",
              "      <td>USE MY GUY SERVICES LLC</td>\n",
              "      <td>4827 E Downing Cir</td>\n",
              "      <td>Mesa</td>\n",
              "      <td>AZ</td>\n",
              "      <td>85205</td>\n",
              "      <td>33.428065</td>\n",
              "      <td>-111.726649</td>\n",
              "      <td>4.5</td>\n",
              "      <td>26</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'ByAppo...</td>\n",
              "      <td>Home Services, Plumbing, Electricians, Handyma...</td>\n",
              "      <td>{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209388</th>\n",
              "      <td>9Q0fPWAjUweoFDk0kafuzQ</td>\n",
              "      <td>Nishi Sushi</td>\n",
              "      <td>9750 Weston Road</td>\n",
              "      <td>Vaughan</td>\n",
              "      <td>ON</td>\n",
              "      <td>L4H 2P2</td>\n",
              "      <td>43.838555</td>\n",
              "      <td>-79.559823</td>\n",
              "      <td>4.0</td>\n",
              "      <td>5</td>\n",
              "      <td>0</td>\n",
              "      <td>{'Ambience': \"{'romantic': False, 'intimate': ...</td>\n",
              "      <td>Japanese, Sushi Bars, Restaurants</td>\n",
              "      <td>{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209389</th>\n",
              "      <td>PotiAhtDMYMNsJCzV0oLAw</td>\n",
              "      <td>Walmart</td>\n",
              "      <td>3240 Wilkinson Blvd</td>\n",
              "      <td>Charlotte</td>\n",
              "      <td>NC</td>\n",
              "      <td>28208</td>\n",
              "      <td>35.226307</td>\n",
              "      <td>-80.893539</td>\n",
              "      <td>2.0</td>\n",
              "      <td>13</td>\n",
              "      <td>0</td>\n",
              "      <td>{'RestaurantsPriceRange2': '1', 'BusinessParki...</td>\n",
              "      <td>Department Stores, Food, Mobile Phones, Fashio...</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209390</th>\n",
              "      <td>SYa2j1boLF8DcGVOYfHPcA</td>\n",
              "      <td>Five Guys</td>\n",
              "      <td>7014-590 E Camelback Rd</td>\n",
              "      <td>Scottsdale</td>\n",
              "      <td>AZ</td>\n",
              "      <td>85251</td>\n",
              "      <td>33.504062</td>\n",
              "      <td>-111.929431</td>\n",
              "      <td>3.5</td>\n",
              "      <td>97</td>\n",
              "      <td>1</td>\n",
              "      <td>{'BusinessAcceptsCreditCards': 'True', 'Restau...</td>\n",
              "      <td>American (New), Food, Burgers, Restaurants, Fa...</td>\n",
              "      <td>{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209391</th>\n",
              "      <td>RSSIsgO00OuWQTRoITacpA</td>\n",
              "      <td>Indian Trail Dog Training</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Indian Trail</td>\n",
              "      <td>NC</td>\n",
              "      <td>28079</td>\n",
              "      <td>35.101965</td>\n",
              "      <td>-80.599385</td>\n",
              "      <td>5.0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Pet Services, Pet Training, Pets</td>\n",
              "      <td>{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>209392</th>\n",
              "      <td>tOcYmewXFhQeZh3V42ymwg</td>\n",
              "      <td>Kudlow Ye</td>\n",
              "      <td>21 St Clair Avenue E, Suite 401</td>\n",
              "      <td>Toronto</td>\n",
              "      <td>ON</td>\n",
              "      <td>M4T 1L9</td>\n",
              "      <td>43.688214</td>\n",
              "      <td>-79.392756</td>\n",
              "      <td>5.0</td>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Tax Services, Professional Services, Accountan...</td>\n",
              "      <td>{'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ...</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>209393 rows × 14 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "                   business_id  ...                                              hours\n",
              "0       f9NumwFMBDn751xgFiRbNA  ...  {'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'...\n",
              "1       Yzvjg0SayhoZgCljUJRF9Q  ...                                                NaN\n",
              "2       XNoUzKckATkOD1hP6vghZg  ...                                                NaN\n",
              "3       6OAZjbxqM5ol29BuHsil3w  ...  {'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ...\n",
              "4       51M2Kk903DFYI6gnB5I6SQ  ...  {'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '...\n",
              "...                        ...  ...                                                ...\n",
              "209388  9Q0fPWAjUweoFDk0kafuzQ  ...  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...\n",
              "209389  PotiAhtDMYMNsJCzV0oLAw  ...                                                NaN\n",
              "209390  SYa2j1boLF8DcGVOYfHPcA  ...  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...\n",
              "209391  RSSIsgO00OuWQTRoITacpA  ...  {'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '...\n",
              "209392  tOcYmewXFhQeZh3V42ymwg  ...  {'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ...\n",
              "\n",
              "[209393 rows x 14 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 7
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "S3nxoHDb-Rhe"
      },
      "source": [
        "df_review = pd.read_csv('/content/drive/My Drive/1001/yelp_reviews.csv')"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ojaupVq2gupp",
        "outputId": "db48278b-aba4-4946-ca61-c7dec3f0f4b9",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "df_review.shape"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(8021124, 18)"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 7
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "YjpjwX71iLHx",
        "outputId": "d53b16de-ee50-4c2f-f4ae-266436d42513",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "df_review.columns"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',\n",
              "       'latitude', 'longitude', 'stars', 'review_count', 'is_open',\n",
              "       'attributes', 'categories', 'hours', 'user_id', 'review_stars', 'text',\n",
              "       'date'],\n",
              "      dtype='object')"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 8
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "vIJuy_SkiSeX",
        "outputId": "e1f48b4c-391f-4806-ce87-a8f595154b5f",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "df_review['business_id'].unique().shape"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(209395,)"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 10
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "iclBTGl3iXYa",
        "outputId": "7a3be8e4-b8d3-426d-9a17-ec0a9f6a9114",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 759
        }
      },
      "source": [
        "df_review[df_review['state'] == 'NY']"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>business_id</th>\n",
              "      <th>name</th>\n",
              "      <th>address</th>\n",
              "      <th>city</th>\n",
              "      <th>state</th>\n",
              "      <th>postal_code</th>\n",
              "      <th>latitude</th>\n",
              "      <th>longitude</th>\n",
              "      <th>stars</th>\n",
              "      <th>review_count</th>\n",
              "      <th>is_open</th>\n",
              "      <th>attributes</th>\n",
              "      <th>categories</th>\n",
              "      <th>hours</th>\n",
              "      <th>user_id</th>\n",
              "      <th>review_stars</th>\n",
              "      <th>text</th>\n",
              "      <th>date</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>409586</th>\n",
              "      <td>XphmlM6c1a2gJ9dDv0MTEQ</td>\n",
              "      <td>US Immigration</td>\n",
              "      <td>234 W Service Rd</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>45.006670</td>\n",
              "      <td>-73.454383</td>\n",
              "      <td>3.5</td>\n",
              "      <td>3.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Public Services &amp; Government</td>\n",
              "      <td>NaN</td>\n",
              "      <td>zFAjzhVWNCCAuDhgHqekzg</td>\n",
              "      <td>3.0</td>\n",
              "      <td>Bon je me dois quand même de faire un petit av...</td>\n",
              "      <td>2014-08-25 18:36:47</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>409587</th>\n",
              "      <td>XphmlM6c1a2gJ9dDv0MTEQ</td>\n",
              "      <td>US Immigration</td>\n",
              "      <td>234 W Service Rd</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>45.006670</td>\n",
              "      <td>-73.454383</td>\n",
              "      <td>3.5</td>\n",
              "      <td>3.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Public Services &amp; Government</td>\n",
              "      <td>NaN</td>\n",
              "      <td>FaJFg9oTgMFDlZk6EOUBJQ</td>\n",
              "      <td>3.0</td>\n",
              "      <td>Main entrance back to the USA, if you follow w...</td>\n",
              "      <td>2017-07-07 18:01:01</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>409588</th>\n",
              "      <td>XphmlM6c1a2gJ9dDv0MTEQ</td>\n",
              "      <td>US Immigration</td>\n",
              "      <td>234 W Service Rd</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>45.006670</td>\n",
              "      <td>-73.454383</td>\n",
              "      <td>3.5</td>\n",
              "      <td>3.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Public Services &amp; Government</td>\n",
              "      <td>NaN</td>\n",
              "      <td>xgX-b91krgTAXQ-UL567Hw</td>\n",
              "      <td>4.0</td>\n",
              "      <td>Make sure you aim to try and avoid between 4-7...</td>\n",
              "      <td>2019-08-10 17:53:41</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>476590</th>\n",
              "      <td>0Ur9usWBEN-fPvMgfmqC1A</td>\n",
              "      <td>Contact Lens King</td>\n",
              "      <td>30 Lawrence Paquette Dr</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.985468</td>\n",
              "      <td>-73.424611</td>\n",
              "      <td>2.0</td>\n",
              "      <td>4.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Shopping, Personal Shopping, Eyewear &amp; Opticia...</td>\n",
              "      <td>{'Monday': '8:30-18:0', 'Tuesday': '8:30-18:0'...</td>\n",
              "      <td>lMAJ_XnXDhF2-WOlw-Whng</td>\n",
              "      <td>5.0</td>\n",
              "      <td>I have to say this company went above and beyo...</td>\n",
              "      <td>2019-06-26 04:35:06</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>476591</th>\n",
              "      <td>0Ur9usWBEN-fPvMgfmqC1A</td>\n",
              "      <td>Contact Lens King</td>\n",
              "      <td>30 Lawrence Paquette Dr</td>\n",
              "      <td>Champlain</td>\n",
              "      <td>NY</td>\n",
              "      <td>12919</td>\n",
              "      <td>44.985468</td>\n",
              "      <td>-73.424611</td>\n",
              "      <td>2.0</td>\n",
              "      <td>4.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>NaN</td>\n",
              "      <td>Shopping, Personal Shopping, Eyewear &amp; Opticia...</td>\n",
              "      <td>{'Monday': '8:30-18:0', 'Tuesday': '8:30-18:0'...</td>\n",
              "      <td>fi2F3fA8w_9z42qTCAnYsA</td>\n",
              "      <td>1.0</td>\n",
              "      <td>Garbage company - beware.\\n\\nPlaced an order w...</td>\n",
              "      <td>2019-08-20 23:35:03</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6538531</th>\n",
              "      <td>7LBGPfgMLMBVpf3KavA0LA</td>\n",
              "      <td>Safari Beauty Studio</td>\n",
              "      <td>9213 165th St</td>\n",
              "      <td>New York</td>\n",
              "      <td>NY</td>\n",
              "      <td>11433</td>\n",
              "      <td>36.045719</td>\n",
              "      <td>-115.313391</td>\n",
              "      <td>4.0</td>\n",
              "      <td>16.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>{'RestaurantsPriceRange2': '2', 'BikeParking':...</td>\n",
              "      <td>Cosmetics &amp; Beauty Supply, Makeup Artists, Wig...</td>\n",
              "      <td>{'Monday': '9:30-19:0', 'Wednesday': '9:30-19:...</td>\n",
              "      <td>zd9btXK9qgDNrbuijdMgjA</td>\n",
              "      <td>5.0</td>\n",
              "      <td>I made a same day appointment for the works ( ...</td>\n",
              "      <td>2017-01-07 01:08:43</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6538532</th>\n",
              "      <td>7LBGPfgMLMBVpf3KavA0LA</td>\n",
              "      <td>Safari Beauty Studio</td>\n",
              "      <td>9213 165th St</td>\n",
              "      <td>New York</td>\n",
              "      <td>NY</td>\n",
              "      <td>11433</td>\n",
              "      <td>36.045719</td>\n",
              "      <td>-115.313391</td>\n",
              "      <td>4.0</td>\n",
              "      <td>16.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>{'RestaurantsPriceRange2': '2', 'BikeParking':...</td>\n",
              "      <td>Cosmetics &amp; Beauty Supply, Makeup Artists, Wig...</td>\n",
              "      <td>{'Monday': '9:30-19:0', 'Wednesday': '9:30-19:...</td>\n",
              "      <td>jAKOHbXpllYH7ojnra91iw</td>\n",
              "      <td>5.0</td>\n",
              "      <td>This was first time at this salon and they all...</td>\n",
              "      <td>2016-02-08 21:55:45</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6538533</th>\n",
              "      <td>7LBGPfgMLMBVpf3KavA0LA</td>\n",
              "      <td>Safari Beauty Studio</td>\n",
              "      <td>9213 165th St</td>\n",
              "      <td>New York</td>\n",
              "      <td>NY</td>\n",
              "      <td>11433</td>\n",
              "      <td>36.045719</td>\n",
              "      <td>-115.313391</td>\n",
              "      <td>4.0</td>\n",
              "      <td>16.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>{'RestaurantsPriceRange2': '2', 'BikeParking':...</td>\n",
              "      <td>Cosmetics &amp; Beauty Supply, Makeup Artists, Wig...</td>\n",
              "      <td>{'Monday': '9:30-19:0', 'Wednesday': '9:30-19:...</td>\n",
              "      <td>3IixTiDfT2KuLsvG9UF3eA</td>\n",
              "      <td>1.0</td>\n",
              "      <td>I came in here, given the reviews on this webs...</td>\n",
              "      <td>2017-09-08 19:40:02</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7037603</th>\n",
              "      <td>7LBGPfgMLMBVpf3KavA0LA</td>\n",
              "      <td>Safari Beauty Studio</td>\n",
              "      <td>9213 165th St</td>\n",
              "      <td>New York</td>\n",
              "      <td>NY</td>\n",
              "      <td>11433</td>\n",
              "      <td>36.045719</td>\n",
              "      <td>-115.313391</td>\n",
              "      <td>4.0</td>\n",
              "      <td>16.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>{'RestaurantsPriceRange2': '2', 'BikeParking':...</td>\n",
              "      <td>Cosmetics &amp; Beauty Supply, Makeup Artists, Wig...</td>\n",
              "      <td>{'Monday': '9:30-19:0', 'Wednesday': '9:30-19:...</td>\n",
              "      <td>teeZvELdaJDjuMEtRI_jCg</td>\n",
              "      <td>5.0</td>\n",
              "      <td>Safari Beauty Studio is a great place to do yo...</td>\n",
              "      <td>2016-07-23 20:44:36</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7037604</th>\n",
              "      <td>7LBGPfgMLMBVpf3KavA0LA</td>\n",
              "      <td>Safari Beauty Studio</td>\n",
              "      <td>9213 165th St</td>\n",
              "      <td>New York</td>\n",
              "      <td>NY</td>\n",
              "      <td>11433</td>\n",
              "      <td>36.045719</td>\n",
              "      <td>-115.313391</td>\n",
              "      <td>4.0</td>\n",
              "      <td>16.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>{'RestaurantsPriceRange2': '2', 'BikeParking':...</td>\n",
              "      <td>Cosmetics &amp; Beauty Supply, Makeup Artists, Wig...</td>\n",
              "      <td>{'Monday': '9:30-19:0', 'Wednesday': '9:30-19:...</td>\n",
              "      <td>F-BDhOy1jbyaef6sNF98lg</td>\n",
              "      <td>5.0</td>\n",
              "      <td>This review is long overdue lol. This salon ca...</td>\n",
              "      <td>2016-04-09 19:49:50</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>316 rows × 18 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "                    business_id  ...                 date\n",
              "409586   XphmlM6c1a2gJ9dDv0MTEQ  ...  2014-08-25 18:36:47\n",
              "409587   XphmlM6c1a2gJ9dDv0MTEQ  ...  2017-07-07 18:01:01\n",
              "409588   XphmlM6c1a2gJ9dDv0MTEQ  ...  2019-08-10 17:53:41\n",
              "476590   0Ur9usWBEN-fPvMgfmqC1A  ...  2019-06-26 04:35:06\n",
              "476591   0Ur9usWBEN-fPvMgfmqC1A  ...  2019-08-20 23:35:03\n",
              "...                         ...  ...                  ...\n",
              "6538531  7LBGPfgMLMBVpf3KavA0LA  ...  2017-01-07 01:08:43\n",
              "6538532  7LBGPfgMLMBVpf3KavA0LA  ...  2016-02-08 21:55:45\n",
              "6538533  7LBGPfgMLMBVpf3KavA0LA  ...  2017-09-08 19:40:02\n",
              "7037603  7LBGPfgMLMBVpf3KavA0LA  ...  2016-07-23 20:44:36\n",
              "7037604  7LBGPfgMLMBVpf3KavA0LA  ...  2016-04-09 19:49:50\n",
              "\n",
              "[316 rows x 18 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 17
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "0bg25rE-tv6C"
      },
      "source": [
        ""
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}